name = "mental-sense-link-project"
type = "javascript"
compatibility_date = "2024-10-13"

[env.production]
workers_dev = true          
compatibility_date = "2024-10-13"

[build]
upload = { 
  format = "service-worker" 
}

[functions]                
directory = "functions"    
